from __future__ import annotations
import os

BINANCE_API_KEY    = os.getenv("BINANCE_API_KEY",    "8A9jCVy39mlTlPZPfYi3AuXjstRrzALqAAqokCBfhkS1GIczs12eZLQUvZw70Zaw")
BINANCE_SECRET_KEY = os.getenv("BINANCE_SECRET_KEY", "oOmgc18vPrK5CA3fRaea9BvI4ZWgIp8W55BSWQWtk61UpB9whZBmGtFUBNpzdwqH")
BINANCE_MARKET_BASE = "https://api.binance.com"
BINANCE_TRADE_BASE  = "https://testnet.binance.vision"
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "YOUR_DISCORD_WEBHOOK_URL_HERE")

SYMBOLS = ["BTCUSDT", "ETHUSDT", "BNBUSDT"]

INITIAL_CAPITAL          = 1000.0
RISK_PER_TRADE_PCT       = 0.015
MAX_CONCURRENT_POSITIONS = 3
DAILY_LOSS_LIMIT_PCT     = 0.03
ATR_PERIOD               = 14
ATR_SL_MULTIPLIER        = 1.5
TP1_RISK_RATIO           = 1.5
TP2_RISK_RATIO           = 3.0
TP1_CLOSE_RATIO          = 0.5

EMA_FAST   = 20
EMA_SLOW   = 50
EMA_TREND  = 200
RSI_PERIOD = 14
RSI_MIN    = 40
RSI_MAX    = 70

SCAN_INTERVAL_MINUTES = 15
